-- MySQL dump 9.09
--
-- Host: localhost    Database: todosCCB
---------------------------------------------------------
-- Server version	4.0.15-max-log

--
-- Table structure for table `idx`
--

DROP TABLE IF EXISTS idx;
CREATE TABLE idx (
  pid varchar(125) NOT NULL default '',
  name varchar(125) NOT NULL default '',
  title varchar(125) NOT NULL default '',
  description text NOT NULL,
  keywords text NOT NULL,
  url varchar(125) NOT NULL default '',
  status varchar(125) NOT NULL default '',
  type varchar(125) NOT NULL default '',
  member_of varchar(125) NOT NULL default '',
  x varchar(125) NOT NULL default '',
  source varchar(125) NOT NULL default '',
  PRIMARY KEY  (pid)
) TYPE=MyISAM;

--
-- Dumping data for table `idx`
--

INSERT INTO idx VALUES ('/Contact_Us/contact_information.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Contact_Us/guest_book.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Contact_Us/guest_log.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/FBR/fbr_bbc.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/FBR/fbr_report_0103.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/FBR/fbr_report_0302.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/FBR/fbr_report_0303.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/FBR/fbr_report_0602.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/FBR/fbr_training_0502.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/FBR/fbr_update_0302.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/FBR/images/jan03captions.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/FBR/mar02relief_report.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/FBR/march02.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Get_Involved/get_involved.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Get_Involved/good_life_club.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Get_Involved/guest_book.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Get_Involved/letter_to_congress.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/images/fbr_20040119_01.jpg','','fbr_20040119_01 (jpg)','','','SELF','1','','','','');
INSERT INTO idx VALUES ('/images/fbr_20040119_02.jpg','','fbr_20040119_02 (jpg)','','','SELF','1','','','','');
INSERT INTO idx VALUES ('/images/fbr_20040119_03.jpg','','fbr_20040119_03 (jpg)','','','SELF','1','','','','');
INSERT INTO idx VALUES ('/images/fbr_20040119_04.jpg','','fbr_20040119_04 (jpg)','','','SELF','1','','','','');
INSERT INTO idx VALUES ('/images/jan03captions.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/News/99827.html','','99827 (html)','','','SELF','1','','','','');
INSERT INTO idx VALUES ('/News/afp_20031018.html','','','Bangkok: Burma\'s junta faces a roasting from US President George W. Bush at next week\'s APEC leaders meetings over the continued detention of opposition leader Aung San Suu Kyi.\r\n','Bangkok: Burma\'s junta faces a roasting from US President George W. Bush at next week\'s APEC leaders meetings over the continued detention of opposition leader Aung San Suu Kyi.\r\n\r\nMr Bush also is expected to urge APEC leaders to do more to push for democratic reforms in Burma, which has been run for four decades by the military. \r\n\r\nMr Bush\'s National Security Adviser, Condoleezza Rice, has said the President will make clear his concern for the welfare of Ms Suu Kyi, who is under house arrest in the Burmese capital, Rangoon. \r\n\r\n\"We have been in constant contact with the UN representative about this and asking that she be visited and that we know her state,\" Dr Rice said this week. \r\n','http://www.theaustralian.news.com.au/common/story_page/0,5744,7592451%255E2703,00.html','1','','','','AFP');
INSERT INTO idx VALUES ('/News/br_update.html','','Br Update (html)','BURMA ARMY ATTACKS ON VILLAGES AND IDPS IN NORTHERN KAREN STATE.','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/erm_20031002.html','','Emergency Relief Mission, Paan District, Karen State, Burma','MISSION PURPOSE:\r\n\r\nTo bring emergency relief, hope, love and compassion to IDPs and villagers in the fighting area of Mae Plae To, Paan District, Karen State, Burma in September/October 2003.  Distribution of aid, presents and medicine provided by the Free Burma Rangers.','FBR','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/fbr_20040116.html','','3,500 new Karen and Karenni IDPs and Burma Army attacks','The Burma Army are now conducting an offensive in the northern Karen State\r\n(Muthraw district) and have burned 2 villages, many rice barns and chased\r\nover 3,500 villagers into the jungle.','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/fbr_20040119.htm','','3500 Driven From Their Homes in Karen State!','Thank you for all your help, love and prayers. We could not do much without you and are grateful that you care about these people here. The following is not a standard report, it is what I feel and what we see here.','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/fbr_report_20031011.html','','Fighting in Paan District,Karen State, Burma','Burma Army Offensive, Code Named, \"Power Over the Land\".\r\n12 Burma Army Battalions and three DKBA battalions are now attacking the KNLA 7th Brigade Headquarters on the Moei River in Paan District, Karen State Burma.','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/fbr_report_20031226.html','','Situation Update: Burmese using un-official cease-fire to reinforce positions in Karen and Karenni States?','Summary: From 1 December through the present time (26 Dec,\'03), there have been numerous clashes between the Burma Army and KNU as well as KNPP forces.\r\nThe Burma Army has increased its road building activities, has burned down two villages and has forced villagers to flee their homes in the northern Karen State and southern Karenni State.\r\n','Karen,Karenni,SLORC','http://www.freeburmarangers.org/Reports/fbr_report_20031226.html','1','','','','FBR');
INSERT INTO idx VALUES ('/News/fbr_report_20040111.html','','Update from Karen/Karenni IDP site: (w pictures)','There are now over 1,000 Karenni IDPs and 1,000 Karen IDPs on the Karen and\r\nKarenni border, just inside northern Muthraw district, Karen State. This is due to ongoing \r\nattacks by the Burma Army.\r\n','','http://www.freeburmarangers.org/Reports/fbr_report_20040112.html','1','','','','FBR');
INSERT INTO idx VALUES ('/News/fbr_report_20040118.html','','Jan 18, 2004 Continued Burma Army Attacks','Three Battalions of the Burma Army LIB 512, LIB 18 and IB 3 are continuing\r\ntheir attacks against Karen villagers in Northern Karen State.There have\r\nalso been clashes between the Burma Army and the Karen National Liberation\r\nArmy (KNLA-KNU).','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/fbr_report_20040126.html','','Ongoing Burma Army offensives in Northern Karen State','On 23 January one Battalion of the Burma Army arrived at Siday village\r\nnorthern Karen State (N 18 41 E 096 59 ). After encountering landmines this\r\nbattalion retreated with an unknown number of casualties. They are now at Bu\r\nSa Kee village, Eastern Toungoo District , Karen State (N 18 44 E 096 57).\r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_bbc.html','','BBC Report: THE FORGOTTEN PEOPLE','PI FOR CORRESPONDENT: THE FORGOTTEN PEOPLE\r\nBBC Report on the Karen:In 1948 Burma became an independent country, that same year its minority people the Karen declared themselves a separate nation - and since then have been fighting a guerrilla war against the government. ','','SELF','1','','','','BBC');
INSERT INTO idx VALUES ('/News/hrr_report_0103.html','','Relief Mission: Internally Displaced Karen of Northern Karen State, Burma.','Trip Report:   Relief Mission: Internally Displaced Karen of Northern Karen State, Burma. \r\nDecember 30, 2002 - January 20, 2003\r\n \r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_report_0302.html','','RELIEF MISSION TO INTERNALLY DISPLACED PERSONS IN THE NORTHERN KAREN STATE, BURMA.','From 24 February to 12 March 2002, a relief team , conducted a humanitarian relief mission to internally displaced Karen in the northern Karen State of Burma. Due to the attacks of the Burma Army there are over 2 million people displaced inside Burma. In the Northern Karen State alone, (Toungoo, Papun, Nyaunglebin and Thaton districts), there are now over 4,000 new internally displaced persons (IDP). \r\n\r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_report_0303.html','','Hrr Report 0303 (html)','The purpose of this relief mission to the South-Eastern Shan States was to bring help, hope and love to the IDPs and villagers of this area. A joint Karen/Karenni Relief Team and a Shan (SSA) relief team conducted a brief (2 weeks), mission in March 2003.','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_report_0602.html','','SITUATION UPDATE: CENTRAL DOOPLAYA DISTRICT, KAREN STATE, BURMA, JUNE 22, 2002.','Civilians massacred, villages burned, churches destroyed, Christian pastors and a Buddhist Monk tortured, forced relocation, and over 5,000 IDPs, 1,000 of whom are in hiding and fleeing for their lives. This is the current situation in central Dooplaya, Karen State, Burma. Dooplaya district is that part of Karen State, Burma, bordering Tak and Kanchanaburi province, Thailand, to the east','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_report_0603.html','','Relief Mission: Paan District of Karen State, Burma','Relief Mission: Paan District of Karen State, Burma\r\nMay 26, 2003 – June 9, 2003.  This area of Paan District is under severe oppression by the Burma Army (BA) and their proxies, the Democratic Karen Buddhist Army, (DKBA). Every village and IDP site visited, reported regular forced labor, beatings and shooting incidents by the Burma army and DKBA. One village had been recently burned down by the DKBA.\r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_report_1101.html','','Situation Report Of The Northern Karen Districts:','1 November 2001 \r\nThis report is a brief update on the situation in northern Karen state. It was completed after a relief mission to the internally displaced people (IDPs) in these areas. The Burma Army continues its attacks against the Karen people of Papun, Taungoo and Nyaunglebin districts (northern Karen state, Burma), destroying rice supplies, torturing and executing villagers, looting villages, relocating people by force, conducting forced labor, and terrorizing the population by the systematic laying of landmines throughout each district.\r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_report_200309.html','','Relief Missions: 2003 IDP Relief Mission Reports','These reports are \r\nfrom teams who were trained earlier in 2003 in a Leadership and Relief Training \r\nand then went to serve their people in the war zones of Burma.These are summaries \r\nof the reports submitted by these teams.','','','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_report_200309a.htm','','Hrr Report 200309a (htm)','Report summaries are from three ethnic teams who completed  Leadership and Relief Training and then went to serve their people in the war zones of Burma.','','SELF','1','','','','CCB');
INSERT INTO idx VALUES ('/News/hrr_report_200309a.html','','Hrr Report 200309a (html)','NORTHERN KAREN STATE- PAAN DISTRICT September 2003','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_report_200309_lahu.html','','Lahu Leadership and Relief Mission-Eastern Shan States September 2003','This report covers rape, narcotics, forced labor, religious persecution and other human rights violations by the Burma Army, as well as a daily mission report.','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_report_20031013.html','','Rape, murder and forced labor: Pa-an district report','This HRV report covers a rape and murder of a Karen woman and the used of forced labor directly related to the ongoing offensive in the eastern Dawna range near the KNLA 7th Brigade HQ.\r\n','','SELF','1','','','','CCB');
INSERT INTO idx VALUES ('/News/hrr_report_lahu_0603.html','','LAHU Free Burma Rangers Relief mission report  JUNE 2003','On June 5, 2003, Tak Mar UWSA-171 (based in Nakawngmu village, Mongton Township ) and Col- Soe Thiang (Burma Army) made an agreement and ordered the villagers as follows. They ordered the young boys (above 15 years old) who are living Mongton areas to enter to the UWSA. They want 4,000 people to become Wa soldiers. So they forcibly collected the villagers. The Wa army said, They will be commandos for the UWSA and SPDC. Thus, the villagers worry about being forced to join the army and they do not want to be Wa soldiers.\r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/hrr_training_0502.html','','Leadership and relief team training - May 2002','Ten teams from the Karen, Karenni, Shan, Pa-O, and Arakan ethnic groups completed leadership and relief training organized by the National Democratic Front (NDF) in the Karen State of Burma. \r\n\r\nThe teams then deployed on relief missions to assist the internally displaced people (IDP) of Burma. The primary purpose of the teams is to give love, hope and emergency assistance to the over one-million ethnic IDPs fleeing attacks of the Burma Army. The teams also work to strengthen civil society through setting an example of service and cooperation. \r\n\r\n','','SELF','1','','','','CCB');
INSERT INTO idx VALUES ('/News/hrr_update_0302.html','','Burma Army Attacks Villages and IDPs in Northern Karen State','On 3 March, 2002, the Burma Army launched an offensive against villagers and IDPs in two Northern districts of the Karen State, Papun and Nyaunglebin districts. These attacks follow the November 2001-January 2002 offensive in the same area. From Nov, 2001 to March, 2002, a total of 30 villages burned.\r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/index_hrr.html','','Index Hrr (html)','Index to FBR Relief Trip reports.','','SELF','1','','','','');
INSERT INTO idx VALUES ('/News/index_hrr.php','','Index Hrr','','','SELF','1','','','','');
INSERT INTO idx VALUES ('/News/joseph_pitts_statement.html','','Statement of Congressman Joseph R. Pitts','Statement of Congressman Joseph R. Pitts \r\n\r\nInternational Relations Subcommittee on Terrorism, Nonproliferation and Human Rights \r\n\r\nHuman Rights in Burma: Fifteen Years Post Military Coup \r\n\r\nOctober 1, 2003\r\n\r\n','','SELF','1','','','','http://www.house.gov/pitts');
INSERT INTO idx VALUES ('/News/karen_update_110101.html','','Situation Report Of The Northern Karen Districts:','1 November 2001 \r\nThis report is a brief update on the situation in northern Karen state. It was completed after a relief mission to the internally displaced people (IDPs) in these areas. The Burma Army continues its attacks against the Karen people of Papun, Taungoo and Nyaunglebin districts (northern Karen state, Burma), destroying rice supplies, torturing and executing villagers, looting villages, relocating people by force, conducting forced labor, and terrorizing the population by the systematic laying of landmines throughout each district. This has resulted in an increase in the numbers of internally displaced in these areas as well as a potential increase in refugees who may arrive in Thailand due to this displacement\r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/latest_updates.html','','Burma -- an overview','Burma is a failed state under the rule of one of the world\'s most repressive regimes. The dictators, known as the State Peace and Development Council (SPDC), continue to oppress their people, cause over 3 million to be displaced (refugees and internally displaced), ruin their economy, perpetuate 51 years of civil war, and have helped to make Burma the world\'s second largest producer of opium and heroin. Burma is also the region\'s leader in methamphetamine production and trafficking. In addition to this, the need for Chinese assistance, (military, political and economic) for their campaign to subjugate all the people of Burma','','SELF','1','','','','');
INSERT INTO idx VALUES ('/News/list_of_senators.htm','','List Of Senators (htm)','List of thirty-five US senators who urged  President George W. Bush to use his upcoming trip to Thailand to further the  cause of democracy in Myanmar\r\n','U.S. Senators urge Bush to promote democracy in Myanmar\r\n Tue Oct 7, 5:26 PM ET\r\nWASHINGTON (AFP) - Thirty-five US senators urged President George W. Bush to use his upcoming trip to Thailand to further the  cause of democracy in Myanmar, which they say has become a serious threat to\r\n regional security. \r\n','SELF','1','','','','US Campaign for Burma');
INSERT INTO idx VALUES ('/News/mar02relief_report.html','','Relief Trip Reports -- March 02','FEBRUARY-MARCH 2002 \r\nGENERAL: \r\nFrom 24 February to 12 March 2002, a relief team (FBR), conducted a humanitarian relief mission to internally displaced Karen in the northern Karen State of Burma. Due to the attacks of the Burma Army there are over 2 million people displaced inside Burma. In the Northern Karen State alone, (Toungoo, Papun, Nyaunglebin and Thaton districts), there are now over 4,000 new internally displaced persons (IDP). \r\n\r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/march02.html','','Leadership and relief team training - May 2002','Latest Reports \r\nLeadership and relief team training - May 2002 \r\n\r\nTen teams from the Karen, Karenni, Shan, Pa-O, and Arakan ethnic groups completed leadership and relief training organized by the National Democratic Front (NDF), and facilitated by the Free Burma Rangers (FBR) from 5 to 26 May 2002 in the Karen State of Burma. \r\n\r\n','','SELF','1','','','','CCB');
INSERT INTO idx VALUES ('/News/message_fbr_leader.html','','A Call to Intercession and Action: June 2003','A Call to Intercession and Action:\r\nThe people of Burma are in dire need of our immediate support and intervention.\r\n \r\nHere is a message from a relief team leader after a mission to the internally displaced people (IDPs) of Burma, during May- June, 2003. It is an eyewitness report from the ground and a call to prayer, thought and action. \r\n\r\n\r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/news_update_20031017.html','','Update-fighting in Paan District,Karen State and IDPs','On the night of October 15, 2003, SPDC forces (12 Burma Army Battalions and 3 DKBA battalions), supported by 120mm, 81mm and 60mm mortars, took control of the Mae Ple Do valley and part of the Eastern Dawna Range (west of Mae La, Thailand). The KNLA defenders withdrew and are reorganizing their forces','On the night of October 15, 2003, SPDC forces (12 Burma Army Battalions and 3 DKBA battalions), supported by 120mm, 81mm and 60mm mortars, took control of the Mae Ple Do valley and part of the Eastern Dawna Range (west of Mae La, Thailand). The KNLA defenders withdrew and are reorganizing their forces. The SPDC forces have now arrived on the banks of the Moei river near the KNLA 7th Brigade HQ (now abandoned). The SPDC forces suffered over 150 casualties(killed and wounded), and the KNLA have suffered 15 wounded. Over 300 prisoners are being used by the SPDC forces in this offensive, as porters and as human minesweepers. At least three verified deaths have occurred when prisoners stepped on landmines as they were forced to advance in front of the Burma Army troops. Escaped prisoners report many more deaths from other mine incidents and beatings by the Burma Army.\r\n \r\nThere are still over 1,500 IDPs (over 400 families), in the upper Mae Ple Do valley. They fled there after the SPDC began this offensive in August. Relief teams were able to reach them earlier, but at this time due to the occupying SPDC forces,it is not possible for teams to get through the SPDC lines. Relief teams will however, continue to find ways to reach the IDPs. These IDPs have remained in hiding and do not desire to go to Thailand as they hope to able to return to their farms and their rice crops which will soon be ready for harvest. They are hoping that the SPDC will retreat or will be unable to control this entire area. The KNLA do have some forces remaining in this area and are providing limited protection for these IDPs. The area is heavily mined and it is difficult for anyone to move at this time.','SELF','1','','','','CCB');
INSERT INTO idx VALUES ('/News/photos_jan_03.html','','Relief Trip Mission, January 03: Photos','Eight year old girl and her sister both wounded in 30 October 2002 Burma Army attack that left her uncle dead and three others wounded \r\n','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/photos_june_02.html','','Photos June 02 (html)','June 10, 2002: Internally Displaced Karen family hiding in the jungle after their home was destroyed by the Burma Army. ','','SELF','1','','','','FBR');
INSERT INTO idx VALUES ('/News/prayer_request_20031013.htm','','Prayer Request 20031013 (htm)','The Karen in Paan district , Karen State, Burma are now under renewed attack','Recently, the dictators of Burma asked monks to fast and pray and to invoke help for all thier efforts.\r\nThe Karen have asked us to pray, they aknowledge they can not stop the Burma Army. We pray to the Lord for the deliverance of the Karen and to a stop to this offensive in Jesus name. We ask that the Burma Army retreats and that the spilling of blood stops on all sides. We pray for all God\'s children in Burma on every side of the conflict. Thank you for your prayers.','SELF','1','','','','CCB');
INSERT INTO idx VALUES ('/News/rogers_04_03.html','','Christian Solidarity Worldwide - Visit to the Thai/Burma Border -- Rogers 04 03','The ethnic minorities in Burma are “living in constant fear; fear of when the Burmese are going to knock on the door,” and the situation in Burma is at a “critical point,” according to the General Secretary of the National Democratic Front (NDF), Zing Cung. No progress has been made in political reform or human rights, and therefore much greater international pressure is required. ','','SELF','1','','','','CSW');
INSERT INTO idx VALUES ('/News/rogers_7_02.html','','A Regime Change in Burma -- Benedict Rogers','By BENEDICT ROGERS\r\n\r\nIt is now well over two months since Burma\'s democracy leader Aung San Suu\r\nKyi was released from house arrest. Yet nothing has changed and, for the\r\nethnic minorities who have been fighting a 53-year struggle for freedom,\r\nthe situation has got worse. It is, according to some, the worst year for\r\nBurma\'s ethnic groups since 1997. But still the world remains almost\r\nsilent about their plight.\r\n','','SELF','1','','','','Asian Wall Street Journal');
INSERT INTO idx VALUES ('/News/senators_urge_president.html','','U.S. Senators urge Bush to promote democracy in Myanmar','Thirty-five US senators urged President George W. Bush to use his upcoming trip to Thailand to further the  cause of democracy in Myanmar, which they say has become a serious threat to regional security. \r\n','Thirty-five US senators urged President George W. Bush\r\n (news - web sites) to use his upcoming trip to Thailand to further the  cause of democracy in Myanmar, which they say has become a serious threat to\r\n regional security. \r\n\r\n\"The United States and all its allies -- particularly Thailand -- must\r\nsustain a full court press on the repressive junta in Rangoon to secure\r\nthe immediate and unconditional release of Burmese democracy leader Daw Aung  San Suu Kyi and her colleagues,\" said Republican Senator Mitch McConnell of\r\nKentucky, referring to Myanmar by its former name Burma.\r\n\r\n','SELF','1','','','','AFP');
INSERT INTO idx VALUES ('/News/Sources/src_burmanetnews.html','','Burma Net News','Providing comprehensive coverage of news and opinion on Burma from around the world. ','','http://www.burmanet.org','1','','','','');
INSERT INTO idx VALUES ('/News/Sources/src_burma_project.html','','Burma Project','Soros Foundation Burma information site.','','http://www.burmaproject.org/','1','','','','');
INSERT INTO idx VALUES ('/News/Sources/src_dvb.html','','Democratic Voice of Burma','Democratic Voice of Burma: Daily News Coverage ','','http://www.dvb.no/','1','','','','');
INSERT INTO idx VALUES ('/News/src_burmanetnews.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/News/src_burma_project.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/News/src_dvb.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/News/test4.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/News/update_paan_20031021.html','','','As of 21 October,2003 the Burma Army has retreated from the KNLA 7th Brigade HQ area. The total Burma Army/DKBA casualties were over 300. The KNLA casualties are 15. There are now over 1,500 IDPs in this area.\r\n','Before this retreat, on the night of October 15, 2003, SPDC forces (12 Burma Army Battalions and 3 DKBA battalions), supported by 120mm, 81mm and 60mm mortars, took control of the Mae Ple Do valley and part of the Eastern Dawna Range (west of Mae La, Thailand). The KNLA defenders withdrew and began to reorganizing their forces. The SPDC forces did arrive on the banks of the Moei river near the KNLA 7th Brigade HQ but then withdrew. According to KNLA reports,the SPDC forces were suffering from low morale and internal dissension and that a sudden change in orders this caused them to withdraw. There are still SPDC forces in the area but most have been withdrawn and the offensive seems to have stopped. The SPDC forces suffered over 300 casualties (killed and wounded), and the KNLA have suffered 15 wounded. Of the 15 KNLA wounded, 10 were from their own land mines. Over 1000 prisoners are being used by the SPDC forces in this offensive, as porters and as human minesweepers. At least three verified deaths have occurred when prisoners stepped on land mines as they were forced to advance in front of the Burma Army troops. Escaped prisoners report many more deaths from other mine incidents and beatings by the Burma Army.\r\n\r\n\r\n IDPs:\r\n\r\n\r\nThere are still over 1,500 IDPs (over 400 families), in the upper Mae Ple Do valley. They fled there after the SPDC began this offensive in August. Relief teams were able to reach them earlier, but at this time due to the occupying SPDC forces,it is not possible for teams to get through the SPDC lines. Relief teams will however, continue to find ways to reach the IDPs. These IDPs have remained in hiding and do not desire to go to Thailand as they hope to able to return to their farms and their rice crops which will soon be ready for harvest. They are hoping that the SPDC will retreat or will be unable to control this entire area. The KNLA do have some forces remaining in this area and are providing limited protection for these IDPs. The area is heavily mined and it is difficult for anyone to move at this time.\r\n','SELF','1','','','','CCB');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/2001/aungsang.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/2001/DOP_2001.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/2001/idp_quotes.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/2001/links.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/2001/medical.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/2001/no_sanctuary.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/2001/paw_htoo.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/2001/wa_narcotics.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/2003/bededagsbrochure_2003_dk.pdf','','Bededagsbrochure 2003 Dk (pdf)','PDF brochure for the Day of Prayer for Burma, 2003 (in Danish)','','SELF','1','','','','');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/2003/day_of_prayer_2003.pdf','','Day Of Prayer 2003 (pdf)','PDF brochure for the Day of Prayer for Burma, 2003','','SELF','1','','','','');
INSERT INTO idx VALUES ('/Prayer/Day_of_Prayer/day_of_prayer_2004.pdf','','Day of Prayer 2004 (pdf)','Day of Prayer 2004 brochure (PDF)','','SELF','1','','','','');
INSERT INTO idx VALUES ('/Prayer/prayer_points.html','','Prayer Points','Prayer concerns outline','','SELF','1','','','','');
INSERT INTO idx VALUES ('/Resources/8_8_88.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Resources/burma_china.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Resources/idp.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Resources/idp_quotes.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Resources/links.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Resources/no_sanctuary.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Resources/resources.html','','Resources','List of resources: links, videos, books, organizations.','','SELF','1','','','','');
INSERT INTO idx VALUES ('/Resources/sanctuary.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Resources/wa_narcotics.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/top.html','','','','','','','','','','');
INSERT INTO idx VALUES ('/Your_Turn/dawson.html','','This Way Lies Our Hope:  A Walk with the Free Burma Rangers','Essay by Laurie Dawson -- Free Burma Housewife','','SELF','1','','','','Laurie Dawson');
INSERT INTO idx VALUES ('/Your_Turn/index.php','','','','','','','','','','');
INSERT INTO idx VALUES ('/Your_Turn/kapi_road_to_jericho.html','','LIFE ON THE ROAD TO JERICHO: Would You Engage or Turn Away?','An Essay','','SELF','1','','','','');
INSERT INTO idx VALUES ('/Your_Turn/prayer.html','','A Prayer for Burma','Prayer from a exiled Karen woman from Burma now living in the United States','','SELF','1','','','','');
INSERT INTO idx VALUES ('/Your_Turn/sarah.html','','A Visit to a Burmese Village','Essay by Sarah, an 8th grade US student','','SELF','1','','','','');

