#!/usr/bin/perl -d -w

## Dump db structure from dev
## To load this back into mysql, use "source <name_of_file>"
## or command line like mysql todosCCB -f < todosCCB.sql

package TODOS::tdMain;
use sqlConf qw(:all);

$outfile = "sql_DB_struct.sql";

system "mv $outfile $outfile.1";
system "echo 'SET FOREIGN_KEY_CHECKS=0;' > $outfile";
system "mysqldump -d $dbase_dev >> $outfile";

#cvs commit -m 'Data updates - Dev' -f sql_DB.sql
#cvs commit -m 'Data updates' -f sql_DB.sql diff.sql sql_archive.sql sql_updates.sql
